workflows:
  ios-workflow:
    name: Fastest Bird iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      # Группы больше не нужны, так как используется App Store Connect API
      groups: []
      vars:
        XCODE_PROJECT: "Fast Bird/Fast Bird.xcodeproj"
        XCODE_SCHEME: "Fast Bird"
        BUNDLE_ID: "com.henquick.birdfast.Fast-Bird"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          # ЗАМЕНИТЕ на ваш email для получения уведомлений о сборке
          - user@example.com
        notify:
          success: true
          failure: true
      # Автоматическая загрузка в App Store Connect через API ключ
      app_store_connect:
        # Используем API ключ, который вы добавили в настройках Codemagic
        auth: api_key
        # Автоматическая загрузка в TestFlight после успешной сборки
        submit_to_testflight: true
        # Группы тестировщиков для TestFlight (опционально, можно добавить позже)
        # beta_groups:
        #   - "Testers"
        #   - "Internal Testers"
